SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) "Nome completo",
CONCAT(
IF(DAY(JH.START_DATE) < 10, CONCAT('0', DAY(JH.START_DATE)), DAY(JH.START_DATE)), '/',
IF(MONTH(JH.START_DATE) < 10, CONCAT('0', MONTH(JH.START_DATE)), MONTH(JH.START_DATE)), '/',
YEAR(JH.START_DATE)) 'Data de início',
CONCAT(
IF(DAY(JH.END_DATE) < 10, CONCAT('0', DAY(JH.END_DATE)), DAY(JH.END_DATE)), '/',
IF(MONTH(JH.END_DATE) < 10, CONCAT('0', MONTH(JH.END_DATE)), MONTH(JH.END_DATE)), '/',
YEAR(JH.END_DATE)) 'Data de rescisão',
ROUND(DATEDIFF(JH.END_DATE, JH.START_DATE)/365 ,2)'Anos trabalhados'
FROM hr.employees E
INNER JOIN hr.job_history JH
ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
ORDER BY `Nome completo`, `Anos trabalhados`;
