-- Ajuda de Italo matos
SELECT JOB_TITLE AS 'Cargo',
ROUND(AVG(MIN_SALARY + MAX_SALARY), 2) AS 'Média salarial',
CASE
WHEN (ROUND(CONVERT(DECIMAL(10, 2), (MIN_SALARY + MAX_SALARY)/2)) >= 2000 AND ROUND(CONVERT(DECIMAL(10, 2), (MIN_SALARY + MAX_SALARY)/2)) <=5800) THEN ('Júnior')
WHEN (ROUND(CONVERT(DECIMAL(10, 2), (MIN_SALARY + MAX_SALARY)/2)) AND ROUND(CONVERT(DECIMAL(10, 2), (MIN_SALARY + MAX_SALARY)/2))) THEN ('Pleno')
WHEN (ROUND(CONVERT(DECIMAL(10, 2), (MIN_SALARY + MAX_SALARY)/2)) AND ROUND(CONVERT(DECIMAL(10, 2), (MIN_SALARY + MAX_SALARY)/2))) THEN ('Sênior')
WHEN (ROUND(CONVERT(DECIMAL(10, 2), (MIN_SALARY + MAX_SALARY)/2)) THEN ('CEO')
END AS 'Senioridade'
FROM hr.jobs
GROUP BY JOB_TITLE;
