DELIMITER $$
CREATE PROCEDURE buscar_media_por_cargo(IN JOB VARCHAR(100))
BEGIN
SELECT ROUND(AVG(E.SALARY), 2) AS 'Média salarial'
FROM employees AS E
INNER JOIN
jobs AS J ON J.JOB_id = E.JOB_ID
WHERE J.JOB_TITLE =  cargo;
END $$

DELIMITER ;
