USE hr;
DELIMITER $$
CRIAR  FUNÇÃO  exibir_quantidade_pessoas_contratadas_por_mes_e_ano (MES INT , ANO INT )
RETORNA INT LÊ DADOS SQL
COMEÇAR
DECLARE QUANTIDADE INT ;
SELECT  COUNT ( * ) FROM funcionários WHERE MONTH (HIRE_DATE) = MES AND YEAR (HIRE_DATE) = ANO
INTO QUANTIDADE;
RETURN QUANTIDADE;
END $$
DELIMITER;