SELECT * FROM hr.employees;
SELECT * FROM hr.jobs;
-- (SUM(E.SALARY) / count(*))

SELECT J.JOB_TITLE AS 'Cargo', CAST(AVG(E.SALARY) AS DECIMAL(10,2)) AS `Média salarial`,
CASE
WHEN CAST(AVG(E.SALARY) AS DECIMAL(10,2)) < 5800 THEN 'Júnior'
WHEN CAST(AVG(E.SALARY) AS DECIMAL(10,2)) BETWEEN 5801 AND 7500 THEN 'Pleno'
WHEN CAST(AVG(E.SALARY) AS DECIMAL(10,2)) BETWEEN 7501 AND 10500 THEN 'Sênior'
WHEN CAST(AVG(E.SALARY) AS DECIMAL(10,2)) > 10500 THEN 'CEO'
ELSE 'erro'
END AS 'Senioridade'
FROM hr.employees E INNER JOIN hr.jobs J
ON E.JOB_ID = J.JOB_ID
GROUP BY JOB_TITLE
ORDER BY `Média salarial`, JOB_TITLE;
