SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS 'Nome completo',
J.JOB_TITLE AS Cargo,
JH.START_DATE AS 'Data de início do cargo',
D.DEPARTMENT_NAME AS Departamento
FROM hr.employees E INNER JOIN hr.jobs J ON E.JOB_ID = J.JOB_ID
INNER JOIN hr.job_history JH ON E.JOB_ID = JH.JOB_ID
INNER JOIN hr.departments D ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) DESC, Cargo;
